// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/buy-items": {
            "get": {
                "description": "Retrieves a list of all BuyItem without pagination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BuyItem"
                ],
                "summary": "Get all BuyItem",
                "responses": {
                    "200": {
                        "description": "List of all BuyItems",
                        "schema": {
                            "$ref": "#/definitions/v1.buyItemResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Service failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Data processing failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update BuyItem handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BuyItem"
                ],
                "summary": "Update existing BuyItem",
                "parameters": [
                    {
                        "description": "Update input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.buyItemUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.buyItemResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create BuyItem handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BuyItem"
                ],
                "summary": "Create new BuyItem",
                "parameters": [
                    {
                        "description": "Create input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.buyItemCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.buyItemResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a BuyItem by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BuyItem"
                ],
                "summary": "Delete a BuyItem",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BuyItem ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content (Successfully deleted)"
                    },
                    "400": {
                        "description": "Bad Request (Invalid ID format)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Deletion failed)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/buy-items/pageable": {
            "get": {
                "description": "Retrieves a paginated list of BuyItem with pagination parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BuyItem"
                ],
                "summary": "Get paginated list of BuyItem",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page (default: 10)",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order, e.g., 'name,asc'",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of BuyItem",
                        "schema": {
                            "$ref": "#/definitions/v1.buyItemResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid pagination parameters or service failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Data processing failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/buys": {
            "get": {
                "description": "Retrieves a list of all Buy without pagination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buy"
                ],
                "summary": "Get all Buy",
                "responses": {
                    "200": {
                        "description": "List of all BuyItems",
                        "schema": {
                            "$ref": "#/definitions/v1.buyResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Service failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Data processing failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Buy handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buy"
                ],
                "summary": "Update existing Buy",
                "parameters": [
                    {
                        "description": "Update input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.buyUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.buyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Buy handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buy"
                ],
                "summary": "Create new Buy",
                "parameters": [
                    {
                        "description": "Create input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.buyCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.buyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a Buy by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buy"
                ],
                "summary": "Delete a Buy",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Buy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content (Successfully deleted)"
                    },
                    "400": {
                        "description": "Bad Request (Invalid ID format)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Deletion failed)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/buys/pageable": {
            "get": {
                "description": "Retrieves a paginated list of Buy with pagination parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buy"
                ],
                "summary": "Get paginated list of Buy",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page (default: 10)",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order, e.g., 'name,asc'",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of Buy",
                        "schema": {
                            "$ref": "#/definitions/v1.buyResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid pagination parameters or service failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Data processing failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/categories": {
            "get": {
                "description": "Retrieves a list of all Category without pagination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Get all Category",
                "responses": {
                    "200": {
                        "description": "List of all BuyItems",
                        "schema": {
                            "$ref": "#/definitions/v1.categoryResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Service failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Data processing failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Category handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Update existing Category",
                "parameters": [
                    {
                        "description": "Update input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.categoryUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.categoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Category handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Create new Category",
                "parameters": [
                    {
                        "description": "Create input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.categoryCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.categoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a Category by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Delete a Category",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content (Successfully deleted)"
                    },
                    "400": {
                        "description": "Bad Request (Invalid ID format)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Deletion failed)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/categories/pageable": {
            "get": {
                "description": "Retrieves a paginated list of Category with pagination parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Get paginated list of Category",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page (default: 10)",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order, e.g., 'name,asc'",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of Category",
                        "schema": {
                            "$ref": "#/definitions/v1.categoryResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid pagination parameters or service failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Data processing failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/clients": {
            "get": {
                "description": "Retrieves a list of all Client without pagination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Get all Client",
                "responses": {
                    "200": {
                        "description": "List of all BuyItems",
                        "schema": {
                            "$ref": "#/definitions/v1.clientResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Service failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Data processing failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Client handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Update existing Client",
                "parameters": [
                    {
                        "description": "Update input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.clientUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.clientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Client handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Create new Client",
                "parameters": [
                    {
                        "description": "Create input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.clientCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.clientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a Client by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Delete a Client",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content (Successfully deleted)"
                    },
                    "400": {
                        "description": "Bad Request (Invalid ID format)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Deletion failed)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/clients/pageable": {
            "get": {
                "description": "Retrieves a paginated list of Client with pagination parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Get paginated list of Client",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page (default: 10)",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order, e.g., 'name,asc'",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of Client",
                        "schema": {
                            "$ref": "#/definitions/v1.clientResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid pagination parameters or service failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Data processing failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/products": {
            "get": {
                "description": "Retrieves a list of all Product without pagination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Get all Product",
                "responses": {
                    "200": {
                        "description": "List of all BuyItems",
                        "schema": {
                            "$ref": "#/definitions/v1.productResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Service failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Data processing failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Product handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Update existing Product",
                "parameters": [
                    {
                        "description": "Update input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.productUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.productResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Product handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Create new Product",
                "parameters": [
                    {
                        "description": "Create input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.productCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.productResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a Product by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Delete a Product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content (Successfully deleted)"
                    },
                    "400": {
                        "description": "Bad Request (Invalid ID format)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Deletion failed)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/products/pageable": {
            "get": {
                "description": "Retrieves a paginated list of Product with pagination parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Get paginated list of Product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page (default: 10)",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order, e.g., 'name,asc'",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of Product",
                        "schema": {
                            "$ref": "#/definitions/v1.productResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid pagination parameters or service failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Data processing failure)",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httputils.ErrorDetail": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "issue": {
                    "type": "string"
                }
            }
        },
        "httputils.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httputils.ErrorDetail"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "pageable.Page": {
            "type": "object",
            "properties": {
                "number": {
                    "description": "Current page number",
                    "type": "integer"
                },
                "size": {
                    "description": "Current page size",
                    "type": "integer"
                },
                "totalElements": {
                    "description": "Total elements in all pages",
                    "type": "integer"
                },
                "totalPages": {
                    "description": "Total pages count",
                    "type": "integer"
                }
            }
        },
        "v1.buyCreateRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "description": "Foreign key referencing the client who made the purchase.",
                    "type": "integer"
                },
                "description": {
                    "description": "Optional description or additional details of the purchase.",
                    "type": "string"
                }
            }
        },
        "v1.buyItemCreateRequest": {
            "type": "object",
            "properties": {
                "buy_id": {
                    "description": "Foreign key referencing the associated purchase.",
                    "type": "integer"
                },
                "price": {
                    "description": "Price per unit of the product at the time of purchase.",
                    "type": "string"
                },
                "product_id": {
                    "description": "Foreign key referencing the purchased product.",
                    "type": "integer"
                },
                "quantity": {
                    "description": "Number of units of the product in the purchase.",
                    "type": "integer"
                }
            }
        },
        "v1.buyItemResponse": {
            "type": "object",
            "properties": {
                "buy_id": {
                    "description": "Foreign key referencing the associated purchase.",
                    "type": "integer"
                },
                "created_at": {
                    "description": "Internal field, creation TS",
                    "type": "string"
                },
                "guid": {
                    "description": "Internal field, UUID of the row",
                    "type": "string"
                },
                "price": {
                    "description": "Price per unit of the product at the time of purchase.",
                    "type": "string"
                },
                "product_id": {
                    "description": "Foreign key referencing the purchased product.",
                    "type": "integer"
                },
                "quantity": {
                    "description": "Number of units of the product in the purchase.",
                    "type": "integer"
                },
                "record_id": {
                    "description": "Primary key for the buy_item table.",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "Internal field, last updated TS",
                    "type": "string"
                }
            }
        },
        "v1.buyItemResponseList": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Payload",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.buyItemResponse"
                    }
                },
                "page": {
                    "description": "Page information (if present)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/pageable.Page"
                        }
                    ]
                }
            }
        },
        "v1.buyItemUpdateRequest": {
            "type": "object",
            "properties": {
                "buy_id": {
                    "description": "Foreign key referencing the associated purchase.",
                    "type": "integer"
                },
                "price": {
                    "description": "Price per unit of the product at the time of purchase.",
                    "type": "string"
                },
                "product_id": {
                    "description": "Foreign key referencing the purchased product.",
                    "type": "integer"
                },
                "quantity": {
                    "description": "Number of units of the product in the purchase.",
                    "type": "integer"
                }
            }
        },
        "v1.buyResponse": {
            "type": "object",
            "properties": {
                "client_id": {
                    "description": "Foreign key referencing the client who made the purchase.",
                    "type": "integer"
                },
                "created_at": {
                    "description": "Internal field, creation TS",
                    "type": "string"
                },
                "description": {
                    "description": "Optional description or additional details of the purchase.",
                    "type": "string"
                },
                "guid": {
                    "description": "Internal field, UUID of the row",
                    "type": "string"
                },
                "record_id": {
                    "description": "Primary key for the buy table.",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "Internal field, last updated TS",
                    "type": "string"
                }
            }
        },
        "v1.buyResponseList": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Payload",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.buyResponse"
                    }
                },
                "page": {
                    "description": "Page information (if present)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/pageable.Page"
                        }
                    ]
                }
            }
        },
        "v1.buyUpdateRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "description": "Foreign key referencing the client who made the purchase.",
                    "type": "integer"
                },
                "description": {
                    "description": "Optional description or additional details of the purchase.",
                    "type": "string"
                }
            }
        },
        "v1.categoryCreateRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the category.",
                    "type": "string"
                },
                "parent_id": {
                    "description": "Reference to the parent category. NULL if it is a root category.",
                    "type": "integer"
                }
            }
        },
        "v1.categoryResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Internal field, creation TS",
                    "type": "string"
                },
                "guid": {
                    "description": "Internal field, UUID of the row",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the category.",
                    "type": "string"
                },
                "parent_id": {
                    "description": "Reference to the parent category. NULL if it is a root category.",
                    "type": "integer"
                },
                "record_id": {
                    "description": "Primary key for the category table.",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "Internal field, last updated TS",
                    "type": "string"
                }
            }
        },
        "v1.categoryResponseList": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Payload",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.categoryResponse"
                    }
                },
                "page": {
                    "description": "Page information (if present)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/pageable.Page"
                        }
                    ]
                }
            }
        },
        "v1.categoryUpdateRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the category.",
                    "type": "string"
                },
                "parent_id": {
                    "description": "Reference to the parent category. NULL if it is a root category.",
                    "type": "integer"
                }
            }
        },
        "v1.clientCreateRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "Unique email address of the client.",
                    "type": "string"
                }
            }
        },
        "v1.clientResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Internal field, creation TS",
                    "type": "string"
                },
                "email": {
                    "description": "Unique email address of the client.",
                    "type": "string"
                },
                "guid": {
                    "description": "Internal field, UUID of the row",
                    "type": "string"
                },
                "record_id": {
                    "description": "Primary key for the client table.",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "Internal field, last updated TS",
                    "type": "string"
                }
            }
        },
        "v1.clientResponseList": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Payload",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.clientResponse"
                    }
                },
                "page": {
                    "description": "Page information (if present)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/pageable.Page"
                        }
                    ]
                }
            }
        },
        "v1.clientUpdateRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "Unique email address of the client.",
                    "type": "string"
                }
            }
        },
        "v1.productCreateRequest": {
            "type": "object",
            "properties": {
                "category_id": {
                    "description": "Foreign key referencing the category to which the product belongs.",
                    "type": "integer"
                },
                "description": {
                    "description": "Detailed description of the product.",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the product.",
                    "type": "string"
                }
            }
        },
        "v1.productResponse": {
            "type": "object",
            "properties": {
                "category_id": {
                    "description": "Foreign key referencing the category to which the product belongs.",
                    "type": "integer"
                },
                "created_at": {
                    "description": "Internal field, creation TS",
                    "type": "string"
                },
                "description": {
                    "description": "Detailed description of the product.",
                    "type": "string"
                },
                "guid": {
                    "description": "Internal field, UUID of the row",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the product.",
                    "type": "string"
                },
                "record_id": {
                    "description": "Primary key for the product table.",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "Internal field, last updated TS",
                    "type": "string"
                }
            }
        },
        "v1.productResponseList": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Payload",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.productResponse"
                    }
                },
                "page": {
                    "description": "Page information (if present)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/pageable.Page"
                        }
                    ]
                }
            }
        },
        "v1.productUpdateRequest": {
            "type": "object",
            "properties": {
                "category_id": {
                    "description": "Foreign key referencing the category to which the product belongs.",
                    "type": "integer"
                },
                "description": {
                    "description": "Detailed description of the product.",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the product.",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
