server:
  Port: 5000
  ReadTimeout: 10s
  WriteTimeout: 10s

logger:
  # console/json
  Format: console
  # debug info warn error
  Level: debug

postgres:
  URL: "postgresql://postgres:postgres@localhost:5432/bookstore?sslmode=disable"
  PoolMax: 10
