drop table if exists all_types_test;
create table all_types_test
(
    record_id             serial primary key,

    -- nullable, without defaults
    bool_arr_col          bool[],
    date_arr_col          date[],
    float4_arr_col        float4[],
    float8_arr_col        float8[],
    int2_arr_col          int2[],
    int4_arr_col          int4[],
    int8_arr_col          int8[],
    numeric_arr_col       numeric[],
    text_arr_col          text[],
    uuid_arr_col          uuid[],
    varchar_arr_col       varchar[],
    bytea_col             bytea,
    int2_col              int2,
    int4_col              int4,
    int8_col              int8,
    decimal_col           decimal,
    numeric_col           numeric,
    float4_col            float4,
    float8_col            float8,
    date_col              date,
    time_col              time,
    timetz_col            timetz,
    timestamp_col         timestamp,
    timestamptz_col       timestamptz,
    interval_col          interval,
    bpchar_col            bpchar,
    char_col              char,
    text_col              text,
    varchar_col           varchar,
    bool_col              bool,
    int4range_col         int4range,
    int8range_col         int8range,
    numrange_col          numrange,
    daterange_col         daterange,
    tsrange_col           tsrange,
    tstzrange_col         tstzrange,
    json_col              json,
    jsonb_col             jsonb,
    name_col              name,
    uuid_col              uuid,

    -- nullable, with defaults
    bool_arr_col_df       bool[]               default '{}',
    date_arr_col_df       date[]               default '{}',
    float4_arr_col_df     float4[]             default '{}',
    float8_arr_col_df     float8[]             default '{}',
    int2_arr_col_df       int2[]               default '{}',
    int4_arr_col_df       int4[]               default '{}',
    int8_arr_col_df       int8[]               default '{}',
    numeric_arr_col_df    numeric[]            default '{}',
    text_arr_col_df       text[]               default '{}',
    uuid_arr_col_df       uuid[]               default '{}',
    varchar_arr_col_df    varchar[]            default '{}',
    bytea_col_df          bytea                default '',
    int2_col_df           int2                 default 0,
    int4_col_df           int4                 default 0,
    int8_col_df           int8                 default 0,
    decimal_col_df        decimal              default 0,
    numeric_col_df        numeric              default 0,
    float4_col_df         float4               default 0,
    float8_col_df         float8               default 0,
    date_col_df           date                 default '0001-01-01',
    time_col_df           time                 default '00:00:00',
    timetz_col_df         timetz               default '00:00:00+00',
    timestamp_col_df      timestamp            default '0001-01-01 00:00:00',
    timestamptz_col_df    timestamptz          default '0001-01-01 00:00:00+00',
    interval_col_df       interval             default '0',
    bpchar_col_df         bpchar               default '',
    char_col_df           char                 default '',
    text_col_df           text                 default '',
    varchar_col_df        varchar              default '',
    bool_col_df           bool                 default false,
    int4range_col_df      int4range            default 'empty'::int4range,
    int8range_col_df      int8range            default 'empty'::int8range,
    numrange_col_df       numrange             default 'empty'::numrange,
    daterange_col_df      daterange            default 'empty'::daterange,
    tsrange_col_df        tsrange              default 'empty'::tsrange,
    tstzrange_col_df      tstzrange            default 'empty'::tstzrange,
    json_col_df           json                 default '{}'::json,
    jsonb_col_df          jsonb                default '{}'::jsonb,
    name_col_df           name                 default '',
    uuid_col_df           uuid                 default gen_random_uuid(),

    -- non-nullable, without defaults
    bool_arr_col_nn       bool[]      not null,
    date_arr_col_nn       date[]      not null,
    float4_arr_col_nn     float4[]    not null,
    float8_arr_col_nn     float8[]    not null,
    int2_arr_col_nn       int2[]      not null,
    int4_arr_col_nn       int4[]      not null,
    int8_arr_col_nn       int8[]      not null,
    numeric_arr_col_nn    numeric[]   not null,
    text_arr_col_nn       text[]      not null,
    uuid_arr_col_nn       uuid[]      not null,
    varchar_arr_col_nn    varchar[]   not null,
    bytea_col_nn          bytea       not null,
    int2_col_nn           int2        not null,
    int4_col_nn           int4        not null,
    int8_col_nn           int8        not null,
    decimal_col_nn        decimal     not null,
    numeric_col_nn        numeric     not null,
    float4_col_nn         float4      not null,
    float8_col_nn         float8      not null,
    date_col_nn           date        not null,
    time_col_nn           time        not null,
    timetz_col_nn         timetz      not null,
    timestamp_col_nn      timestamp   not null,
    timestamptz_col_nn    timestamptz not null,
    interval_col_nn       interval    not null,
    bpchar_col_nn         bpchar      not null,
    char_col_nn           char        not null,
    text_col_nn           text        not null,
    varchar_col_nn        varchar     not null,
    bool_col_nn           bool        not null,
    int4range_col_nn      int4range   not null,
    int8range_col_nn      int8range   not null,
    numrange_col_nn       numrange    not null,
    daterange_col_nn      daterange   not null,
    tsrange_col_nn        tsrange     not null,
    tstzrange_col_nn      tstzrange   not null,
    json_col_nn           json        not null,
    jsonb_col_nn          jsonb       not null,
    name_col_nn           name        not null,
    uuid_col_nn           uuid        not null,

    -- non-nullable, with defaults
    bool_arr_col_nn_df    bool[]      not null default '{}',
    date_arr_col_nn_df    date[]      not null default '{}',
    float4_arr_col_nn_df  float4[]    not null default '{}',
    float8_arr_col_nn_df  float8[]    not null default '{}',
    int2_arr_col_nn_df    int2[]      not null default '{}',
    int4_arr_col_nn_df    int4[]      not null default '{}',
    int8_arr_col_nn_df    int8[]      not null default '{}',
    numeric_arr_col_nn_df numeric[]   not null default '{}',
    text_arr_col_nn_df    text[]      not null default '{}',
    uuid_arr_col_nn_df    uuid[]      not null default '{}',
    varchar_arr_col_nn_df varchar[]   not null default '{}',
    bytea_col_nn_df       bytea       not null default '',
    int2_col_nn_df        int2        not null default 0,
    int4_col_nn_df        int4        not null default 0,
    int8_col_nn_df        int8        not null default 0,
    decimal_col_nn_df     decimal     not null default 0,
    numeric_col_nn_df     numeric     not null default 0,
    float4_col_nn_df      float4      not null default 0,
    float8_col_nn_df      float8      not null default 0,
    date_col_nn_df        date        not null default '0001-01-01',
    time_col_nn_df        time        not null default '00:00:00',
    timetz_col_nn_df      timetz      not null default '00:00:00+00',
    timestamp_col_nn_df   timestamp   not null default '0001-01-01 00:00:00',
    timestamptz_col_nn_df timestamptz not null default '0001-01-01 00:00:00+00',
    interval_col_nn_df    interval    not null default '0',
    bpchar_col_nn_df      bpchar      not null default '',
    char_col_nn_df        char        not null default '',
    text_col_nn_df        text        not null default '',
    varchar_col_nn_df     varchar     not null default '',
    bool_col_nn_df        bool        not null default false,
    int4range_col_nn_df   int4range   not null default 'empty'::int4range,
    int8range_col_nn_df   int8range   not null default 'empty'::int8range,
    numrange_col_nn_df    numrange    not null default 'empty'::numrange,
    daterange_col_nn_df   daterange   not null default 'empty'::daterange,
    tsrange_col_nn_df     tsrange     not null default 'empty'::tsrange,
    tstzrange_col_nn_df   tstzrange   not null default 'empty'::tstzrange,
    json_col_nn_df        json        not null default '{}'::json,
    jsonb_col_nn_df       jsonb       not null default '{}'::jsonb,
    name_col_nn_df        name        not null default '',
    uuid_col_nn_df        uuid        not null default gen_random_uuid()
);
