drop table if exists all_types_test;
create table all_types_test
(
    id              serial primary key,
    bool_arr_col    bool[]      default '{}',
    date_arr_col    date[]      default '{}',
    float4_arr_col  float4[]    default '{}',
    float8_arr_col  float8[]    default '{}',
    int2_arr_col    int2[]      default '{}',
    int4_arr_col    int4[]      default '{}',
    int8_arr_col    int8[]      default '{}',
    numeric_arr_col numeric[]   default '{}',
    text_arr_col    text[]      default '{}',
    uuid_arr_col    uuid[]      default '{}',
    varchar_arr_col varchar[]   default '{}',
    bytea_col       bytea       default '',
    smallserial_col smallserial,
    serial_col      serial,
    bigserial_col   bigserial,
    int2_col        int2        default 0,
    int4_col        int4        default 0,
    int8_col        int8        default 0,
    decimal_col     decimal     default 0,
    numeric_col     numeric     default 0,
    float4_col      float4      default 0,
    float8_col      float8      default 0,
    date_col        date        default '0001-01-01',
    time_col        time        default '00:00:00',
    timetz_col      timetz      default '00:00:00+00',
    timestamp_col   timestamp   default '0001-01-01 00:00:00',
    timestamptz_col timestamptz default '0001-01-01 00:00:00+00',
    interval_col    interval    default '0',
    bpchar_col      bpchar      default '',
    char_col        char        default '',
    text_col        text        default '',
    varchar_col     varchar     default '',
    bool_col        bool        default false,
    int4range_col   int4range   default 'empty'::int4range,
    int8range_col   int8range   default 'empty'::int8range,
    numrange_col    numrange    default 'empty'::numrange,
    daterange_col   daterange   default 'empty'::daterange,
    tsrange_col     tsrange     default 'empty'::tsrange,
    tstzrange_col   tstzrange   default 'empty'::tstzrange,
    json_col        json        default '{}'::json,
    jsonb_col       jsonb       default '{}'::jsonb,
    name_col        name        default ''
);
